Repository psf/black, pull requests merged in 2020-11, with the labels that each got.

#1743 Automatically build and upload binaries on release
  .github/workflows/upload_binary.yml
  .travis.yml
  CHANGES.md
Labels: cleanup, installation

#1775 Use lowercase hex numbers fixes #1692
  .gitignore
  CHANGES.md
  src/black/__init__.py
  src/black_primer/primer.json
  src/blib2to3/pytree.py
  test_requirements.txt
  tests/data/numeric_literals.py
  tests/data/numeric_literals_py2.py
  tests/data/numeric_literals_skip_underscores.py
Labels: hacktoberfest-accepted

#1780 Provide a stdin-filename to allow stdin to respect force-exclude rules
  README.md
  docs/change_log.md
  src/black/__init__.py
  tests/test_black.py
Labels: command line

#1835 Allow same RHS expressions in annotated assignments as in regular assignments
  CHANGES.md
  src/blib2to3/Grammar.txt
  tests/data/python38.py
Labels: lib2to3

#1839 Switch back to Python 3.8 for ReadTheDocs
  readthedocs.yml
Labels: documentation
