Repository psf/black, pull requests merged in 2020-05, with the labels that each got.

#1132 Improve String Handling
  black.py
  blib2to3/pgen2/pgen.py
  blib2to3/pgen2/tokenize.py
  gallery/gallery.py
  tests/data/cantfit.py
  tests/data/comments4.py
  tests/data/comments6.py
  tests/data/comments7.py
  tests/data/composition.py
  tests/data/long_strings.py
  tests/data/long_strings__edge_case.py
  tests/data/long_strings__regression.py
  tests/data/string_quotes.py
  tests/test_black.py
Labels: stable

#1371 Add Black compatible configurations in documentation (#1366 & #1205)
  README.md
  docs/compatible_configs.md
Labels: documentation

#1330 Add purcell/reformatter.el as an Emacs integration option
  README.md
Labels: documentation

#1317 Adding documentation to the README for import errors in vim
  .gitignore
  README.md
Labels: documentation

#1395 Add py.typed file.
  setup.py
  src/black/py.typed
Labels: enhancement

#1401 Remove no longer used appveyor config
  .appveyor.yml
Labels: cleanup

#1402 Add primer CI tool 🏴
  setup.py
  src/black_primer/cli.py
  src/black_primer/lib.py
  src/black_primer/primer.json
Labels: enhancement

#1427 Add `black-primer` docs
  README.md
  docs/index.rst
Labels: documentation

#1456 Refactor docs / Maintenance of docs
  README.md
  docs/authors.md
  docs/black_primer.md
  docs/blackd.md
  docs/change_log.md
  docs/conf.py
  docs/contributing.md
  docs/contributing_to_black.md
  docs/editor_integration.md
  docs/ignoring_unmodified_files.md
  docs/index.rst
  docs/installation_and_usage.md
  docs/license.md
  docs/pyproject_toml.md
  docs/show_your_style.md
  docs/testimonials.md
  docs/the_black_code_style.md
  docs/version_control_integration.md
Labels: documentation

#1459 Update CONTRIBUTION.md with pre-commit + black-primer instructions
  CONTRIBUTING.md
Labels: documentation
