Repository psf/black, pull requests merged in 2020-10, with the labels that each got.

#1761 Add blackd to nicely exit if missing aiohttp deps
  src/blackd/__init__.py
Labels: dependencies, installation

#1755 Allow black's Github action params overriding.
  README.md
  action.yml
  action/Dockerfile
  action/entrypoint.sh
  docs/authors.md
  docs/github_actions.md
Labels: integrations

#1769 Update PyCharm integrations instructions to avoid running on external changes
  docs/editor_integration.md
Labels: documentation

#1774 docs: fix inline code style
  docs/the_black_code_style.md
Labels: documentation

#1783 Document some culprits with pre-commit
  docs/version_control_integration.md
Labels: documentation, integrations
