Repository psf/black, pull requests merged in 2020-12, with the labels that each got.

#1733 Add quiet flag so non-error actions go unreported
  docs/editor_integration.md
  plugin/black.vim
Labels: vim

#1867 Remove all trace of flake8-mypy
  Pipfile
  Pipfile.lock
  mypy.ini
Labels: cleanup, dependencies

#1885 fix format_str() docstring to prevent users from running into NameError
  src/black/__init__.py
Labels: documentation

#1887 Bump mypy to 0.780 in pre-commit config
  .pre-commit-config.yaml
  src/black_primer/lib.py
Labels: dependencies

#1895 Bump minimum_pre_commit_version per recommendation
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
Labels: bug
