Repository psf/black, pull requests merged in 2021-05, with the labels that each got.

#2173 Add ability to pass posargs to pytest run in tox.ini
  tox.ini
Labels: maintenance, skip news

#2175 Fix Primer: Tox has been formatted with Black 21.4b0
  src/black_primer/primer.json
Labels: skip news

#2185 primer: Renable pandas
  src/black_primer/primer.json
Labels: skip news

#2187 primer: Add `--no-diff` option
  CHANGES.md
  src/black_primer/cli.py
  src/black_primer/lib.py
  tests/test_primer.py
Labels: command line, enhancement, integrations

#2190 Add test configuration that doesn't contain python2 optional install
  pyproject.toml
  tests/test_black.py
  tests/test_format.py
  tox.ini
Labels: skip news

#2186 Drop Travis CI and migrate Coveralls
  .coveragerc
  .github/workflows/test.yml
  .travis.yml
  README.md
  docs/conf.py
Labels: cleanup, skip news

#2180 compatible isort config: mention profile first
  docs/compatible_configs.md
Labels: documentation, skip news

#2191 GHA: Use pre-commit/action to simplify CI
  .github/workflows/lint.yml
Labels: skip news

#2192 Update CHANGES.md for 21.5b0 release
  CHANGES.md
Labels: skip news

#2195 Disable pandas while we look into #2193
  src/black_primer/primer.json
Labels: skip news

#2184 Enable ` --experimental-string-processing` on most primer projects
  src/black_primer/lib.py
  src/black_primer/primer.json
Labels: skip news

#2119 Simplify GitHub Action entrypoint (#1909)
  README.md
  action.yml
  action/entrypoint.sh
Labels: C: integrations, skip news

#2202 Fix broken Action entrypoint
  action/entrypoint.sh
Labels: C: integrations, skip news

#2203 Use optional tests for "no_python2" to simplify local testing
  pyproject.toml
  tests/conftest.py
  tests/optional.py
  tests/test_black.py
  tox.ini
Labels: skip news

#2204 Mark blackd tests with the `blackd` optional marker
  Pipfile
  pyproject.toml
  setup.py
  tests/test_blackd.py
  tests/util.py
Labels: C: maintenance, skip news

#2196 Speed up test suite via distributed testing
  .coveragerc
  .github/workflows/test.yml
  test_requirements.txt
  tox.ini
Labels: C: maintenance, skip news

#2206 Refactor `src/black/__init__.py` into many files
  CHANGES.md
  src/black/__init__.py
  src/black/brackets.py
  src/black/cache.py
  src/black/comments.py
  src/black/concurrency.py
  src/black/const.py
  src/black/debug.py
  src/black/files.py
  src/black/linegen.py
  src/black/lines.py
  src/black/mode.py
  src/black/nodes.py
  src/black/numerics.py
  src/black/output.py
  src/black/parsing.py
  src/black/report.py
  src/black/rusty.py
  src/black/strings.py
  src/black/trans.py
  tests/test_black.py
  tests/test_format.py
  tests/util.py
Labels: C: cleanup, C: maintenance

#2205 Speed up tests even more
  tests/test_black.py
  tests/test_format.py
Labels: C: maintenance, skip news

#2174 Reorganize docs v2
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  AUTHORS.md
  CHANGES.md
  CONTRIBUTING.md
  Pipfile
  Pipfile.lock
  README.md
  docs/authors.md
  docs/black_primer.md
  docs/conf.py
  docs/contributing/gauging_changes.md
  docs/contributing/index.rst
  docs/contributing/reference/reference_classes.rst
  docs/contributing/reference/reference_exceptions.rst
  docs/contributing/reference/reference_functions.rst
  docs/contributing/reference/reference_summary.rst
  docs/contributing/the_basics.md
  docs/getting_started.md
  docs/github_actions.md
  docs/guides/index.rst
  docs/guides/introducing_black_to_your_project.md
  docs/guides/using_black_with_other_tools.md
  docs/index.rst
  docs/installation_and_usage.md
  docs/integrations/editors.md
  docs/integrations/github_actions.md
  docs/integrations/index.rst
  docs/integrations/source_version_control.md
  docs/license.rst
  docs/pyproject_toml.md
  docs/requirements.txt
  docs/show_your_style.md
  docs/the_black_code_style/current_style.md
  docs/the_black_code_style/future_style.md
  docs/the_black_code_style/index.rst
  docs/usage_and_configuration/black_as_a_server.md
  docs/usage_and_configuration/file_collection_and_discovery.md
  docs/usage_and_configuration/index.rst
  docs/usage_and_configuration/the_basics.md
  docs/version_control_integration.md
Labels: C: maintenance, T: documentation

#2207 Fix autodoc refs broken by refactor
  docs/contributing/reference/reference_classes.rst
  docs/contributing/reference/reference_exceptions.rst
  docs/contributing/reference/reference_functions.rst
Labels: C: cleanup, T: documentation, skip news

#2209 Stop docker CI from looking for 'master' branch
  .github/workflows/docker.yml
Labels: skip news

#2212 Autogenerate black(d|-primer)? help in usage docs
  .github/workflows/doc.yml
  .readthedocs.yaml
  Pipfile
  Pipfile.lock
  docs/conf.py
  docs/contributing/gauging_changes.md
  docs/requirements.txt
  docs/usage_and_configuration/black_as_a_server.md
  docs/usage_and_configuration/the_basics.md
Labels: T: documentation, skip news

#2208 Cover more in the usage docs
  docs/usage_and_configuration/the_basics.md
Labels: T: documentation, skip news

#2214 Release process docs
  docs/contributing/index.rst
  docs/contributing/release_process.md
Labels: T: documentation, skip news

#2224 Add stable tag process to release process documentation
  docs/contributing/release_process.md
Labels: T: documentation, skip news

#2221 Remove useless flake8 config + test support code
  .flake8
  tests/test_black.py
Labels: C: cleanup, skip news

#2226 Modify when Test, Primer, and Documentation Build run
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/doc.yml
  .github/workflows/primer.yml
  .github/workflows/test.yml
Labels: C: maintenance, skip news

#2231 Add lower bound for aiohttp-cors + fix primer
  CHANGES.md
  setup.py
  src/black_primer/primer.json
Labels: C: installation / packaging, C: maintenance

#2236 Add issue triage documentation
  Pipfile
  Pipfile.lock
  docs/conf.py
  docs/contributing/index.rst
  docs/contributing/issue_triage.md
  docs/requirements.txt
Labels: C: maintenance, T: documentation, skip news

#2244 Make Prettier preserve line ending type
  .pre-commit-config.yaml
  .prettierrc.yaml
Labels: skip news

#2245 Fix test requirements file name in documentation
  docs/contributing/the_basics.md
Labels: skip news

#2246 Link isort profile to Black code style mention
  docs/the_black_code_style/current_style.md
Labels: C: cleanup, T: documentation, skip news

#2198 Build macOS releases
  .github/workflows/upload_binary.yml
  CHANGES.md
Labels: C: installation / packaging, T: enhancement

#2249 Removed adding a space into empty docstrings.
  CHANGES.md
  src/black/linegen.py
  tests/data/docstring.py
Labels: F: strings / docstrings

#2262 Fix and test docs on Windows
  .github/workflows/doc.yml
  CHANGES.md
  docs/authors.md
  docs/change_log.md
  docs/conf.py
Labels: C: maintenance, T: documentation

#2260 Use latest Python in uploading binaries
  .github/workflows/upload_binary.yml
  CHANGES.md
Labels: C: maintenance

#2269 Issue templates: use HTML comments
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/style_issue.md
Labels: skip news

#2275 Fix path_empty()
  src/black/__init__.py
Labels: skip news

#2276 [primer] ptr no longer requires changes
  src/black_primer/primer.json
Labels: skip news

#2290 Update CHANGES.md for 21.5b2 release
  CHANGES.md
Labels: skip news
