Repository psf/black, pull requests merged in 2021-11, with the labels that each got.

#2583 Update CHANGES.md for 21.10b0 release
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2590 Add a missing space
  src/black/__init__.py
Labels: skip news

#2602 primer: Hypothesis now requires Python>=3.8
  .gitignore
  src/black_primer/primer.json
Labels: skip news, C: maintenance

#2603 Fix typos
  CHANGES.md
  docs/the_black_code_style/index.rst
Labels: skip news

#2605 Bump deps in Pipfile.lock
  Pipfile.lock
Labels: skip news, C: maintenance

#2586 black/parser: partial support for pattern matching
  CHANGES.md
  src/black/linegen.py
  src/black/mode.py
  src/black/parsing.py
  src/blib2to3/Grammar.txt
  src/blib2to3/pgen2/driver.py
  src/blib2to3/pgen2/grammar.py
  src/blib2to3/pgen2/parse.py
  src/blib2to3/pgen2/pgen.py
  src/blib2to3/pygram.py
  tests/data/parenthesized_context_managers.py
  tests/data/pattern_matching_complex.py
  tests/data/pattern_matching_simple.py
  tests/test_format.py
Labels: C: blib2to3, C: parser

#2608 black/parser: support as-exprs within call args
  src/blib2to3/Grammar.txt
  tests/data/pattern_matching_extras.py
  tests/test_format.py
Labels: skip news

#2562 Declare support for Python 3.10
  CHANGES.md
  setup.py
Labels: C: installation / packaging

#2611 black/parser: optimize deepcopying nodes
  src/blib2to3/pytree.py
  tests/data/pattern_matching_extras.py
Labels: skip news

#2412 Docker image usage description
  docs/usage_and_configuration/black_docker_image.md
  docs/usage_and_configuration/index.rst
Labels: T: documentation, C: installation / packaging, skip news

#2431 Implementing mypyc support pt. 2
  mypy.ini
  pyproject.toml
  setup.py
  src/black/__init__.py
  src/black/brackets.py
  src/black/comments.py
  src/black/files.py
  src/black/handle_ipynb_magics.py
  src/black/linegen.py
  src/black/mode.py
  src/black/nodes.py
  src/black/output.py
  src/black/parsing.py
  src/black/strings.py
  src/black/trans.py
  src/black_primer/cli.py
  src/blib2to3/README
  src/blib2to3/pgen2/driver.py
  src/blib2to3/pgen2/parse.py
  src/blib2to3/pgen2/tokenize.py
  src/blib2to3/pytree.py
  tests/test_black.py
Labels: C: performance, skip news

#2614 Fix 3.10's supported features
  src/black/mode.py
Labels: skip news

#2615 fix vim plugin
  plugin/black.vim
Labels: skip news

#2616 prepare release 21.11b0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2622 prepare release 2021.11b1
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2628 Fix mypyc compatibility issue
  src/black/parsing.py
Labels: skip news

#2632 Change `cfg` to `ini` for text highlighting
  docs/guides/using_black_with_other_tools.md
Labels: skip news

#2638 README: Add KeepTruckin to the list of orgs
  README.md
Labels: skip news

#2643 fix regex in test_black.py
  tests/test_black.py
Labels: skip news

#2650 add missing f-string
  src/black/handle_ipynb_magics.py
Labels: skip news

#2657 Remove hidden import from PyInstaller build
  .github/workflows/upload_binary.yml
Labels: skip news

#2645 add FAQ entry about undetected syntax errors
  docs/faq.md
Labels: skip news
