Repository psf/black, pull requests merged in 2021-08, with the labels that each got.

#2411 Fix type dependencies of mypy invocation
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  src/black/files.py
Labels: skip news

#2423 fix: remove unneccessary escape character
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip news

#2425 Update language server links
  docs/integrations/editors.md
Labels: T: documentation, skip news

#2419 Add jupyter deps to Pipfile.lock
  Pipfile
  Pipfile.lock
Labels: skip news

#2437 Improve f-string expression detection regex so ...
  CHANGES.md
  src/black/strings.py
  tests/data/string_quotes.py
Labels: F: strings / docstrings

#2436 Add test requirements to Pipfile[.lock] & bump deps
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  docs/requirements.txt
Labels: skip news, C: maintenance

#2429 Add cpython Lib/ repository config into primer config - Disabled
  src/black_primer/lib.py
  src/black_primer/primer.json
  tests/test_primer.py
Labels: skip news, C: maintenance

#2455 set mypy_path in mypy.ini
  mypy.ini
Labels: skip news

#2454 Add test which covers stdin filename ipynb
  tests/test_black.py
Labels: skip news

#2458 Prepare CHANGES.md for release 21.8b0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2460 Exclude broken typing-extensions version + fix import
  CHANGES.md
  setup.py
  src/black/handle_ipynb_magics.py
Labels: C: dependencies

#2461 fix: run pypi upload from published draft releases
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docker.yml
  .github/workflows/pypi_upload.yml
Labels: skip news

#2468 Change docker workflow for latest_release tag
  .github/workflows/docker.yml
Labels: skip news
