Repository psf/black, pull requests merged in 2021-07, with the labels that each got.

#2358 DOC fixup github actions md
  docs/integrations/github_actions.md
Labels: T: documentation, skip news

#2356 Avoid src being marked as optional in help
  src/black/__init__.py
Labels: skip news

#2363 Use setuptools.find_packages in setup
  setup.py
  src/black_primer/__init__.py
  src/black_primer/cli.py
  tests/test_primer.py
Labels: C: maintenance, skip news

#2369 Second run of tox -e py results in a test error for test marked with no_python2
  tox.ini
Labels: skip news

#2362 Don't include profiling/ to cut down sdist by ~2x
  MANIFEST.in
Labels: C: maintenance, skip news

#2376 Update CHANGES.md for 21.7b0 release
  CHANGES.md
Labels: skip news

#2377 add context manager to temporarily change the cwd
  tests/test_black.py
  tests/util.py
Labels: skip news

#2390 isort docs have changed urls
  docs/guides/using_black_with_other_tools.md
Labels: skip news

#2398 Clarify contributing docs
  docs/contributing/index.rst
Labels: T: documentation, skip news

#2400 Add ESP to sqlalchemy for black-primer
  src/black_primer/primer.json
Labels: C: maintenance, skip news

#2406 Test on Python 3.10-dev
  .github/workflows/fuzz.yml
  .github/workflows/primer.yml
  .github/workflows/test.yml
  tox.ini
Labels: skip news
