Repository psf/black, pull requests merged in 2021-09, with the labels that each got.

#2477 Remove `blackcellmagic` reference
  docs/integrations/editors.md
Labels: skip news

#2494 Update CHANGES.md for 21.9b0 release
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2501 fix all b904s
  src/black/__init__.py
  src/black/linegen.py
  src/blackd/__init__.py
Labels: skip news

#2459 add check for version in the-basics example
  .pre-commit-config.yaml
  scripts/check_version_in_basics_example.py
Labels: skip news

#2481 DOC: cleanup pre-commit instructions following #2430
  docs/integrations/source_version_control.md
Labels: skip news

#2502 Add Kedro to project list and QuantumBlack to orgs
  README.md
Labels: skip news

#2471 add test to cover when unable to replace magics
  src/black/handle_ipynb_magics.py
  tests/test_ipynb.py
Labels: skip news

#2511 MNT: fix python_version markers in Pipfile.lock
  Pipfile
  Pipfile.lock
Labels: C: dependencies, skip news

#1319 Allow to pass the FileMode options in the vim plugin
  CHANGES.md
  autoload/black.vim
  docs/integrations/editors.md
  plugin/black.vim
Labels: C: vim
