Repository psf/black, pull requests merged in 2021-03, with the labels that each got.

#1753 Add ALE
  docs/editor_integration.md
Labels: documentation

#2025 Add missing changelog entry for fmt: skip
  CHANGES.md
Labels: documentation

#1157 Use vim autoload script
  autoload/black.vim
  plugin/black.vim
Labels: vim

#2056 Fix indentation in docs/editor_integration.md
  docs/editor_integration.md
Labels: documentation

#2057 Add a GitHub CHANGELOG/News Check
  .github/workflows/changelog.yml
Labels: skip news

#2061 Add entry for `--extend-exclude` in the right place
  CHANGES.md
Labels: documentation, skip news

#2072 GREP for PR reference accepts references that are split over a line
  .github/workflows/changelog.yml
Labels: skip news
