Repository psf/black, pull requests merged in 2021-04, with the labels that each got.

#1899 Support for top-level user configuration
  README.md
  docs/pyproject_toml.md
  src/black/__init__.py
  src/black_primer/lib.py
  tests/test_black.py
Labels: command line

#1848 Add a GitHub Action to build + Upload black to PyPI
  .github/workflows/lint.yml
  .github/workflows/pypi_upload.yml
  .pre-commit-config.yaml
Labels: installation, skip news

#2073 Add CONTRBUTING info about CHANGES.md requirement
  .github/workflows/changelog.yml
  CONTRIBUTING.md
Labels: documentation, skip news

#2080 Push contributors to use Next PR Number
  CONTRIBUTING.md
  docs/contributing_to_black.md
Labels: documentation, skip news

#2081 Run lint/typechecking in latest python + update pre-commit
  .github/workflows/lint.yml
  .pre-commit-config.yaml
Labels: skip news

#2085 Get rid of redundant spaces in docs
  README.md
  src/black/__init__.py
Labels: skip news

#1916 Add `black` Dockerfile
  Dockerfile
Labels: skip news

#2096 Fix error from upcoming typeshed change
  src/black/__init__.py
Labels: skip news

#2098 fix typing issue around lru_cache arguments
  src/black/__init__.py
Labels: skip news

#1734 Added not formatting files in gitignore (psf#1682)
  docs/pyproject_toml.md
Labels: documentation

#2100 Add missing instructions to make test passed
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip news

#2112 Fix small comment typo
  src/black/__init__.py
Labels: skip news

#2109 Instructions on documenting code style modifications
  CONTRIBUTING.md
Labels: documentation, skip news

#2106 Document experimental string processing and docstring indentation
  docs/the_black_code_style.md
  tests/data/docstring.py
Labels: documentation, skip news

#2086 Add Docker Github Action
  .github/workflows/docker.yml
Labels: enhancement, skip news

#2128 Docker CI: Add missed Checkout step
  .github/workflows/docker.yml
Labels: bug, skip news

#2127 Issue 1629 has been closed, let's celebrate!
  CHANGES.md
Labels: skip news

#2129 Update CHANGES.md for release
  CHANGES.md
Labels: skip news

#2133 Remove Lowercase Hex (PR #1692) from CHANGES.md
  CHANGES.md
  src/black_primer/primer.json
Labels: documentation, skip news

#2146 Symlink docs/change_log.md to CHANGES.md, don't copy
  docs/change_log.md
  docs/conf.py
Labels: documentation, skip news

#2147 Add more tests for fancy whitespace
  CHANGES.md
  tests/data/docstring.py
  tests/data/docstring_no_string_normalization.py
Labels: skip news

#2148 Stop stripping parens in even more illegal spots
  src/black/__init__.py
  tests/data/pep_572_do_not_remove_parens.py
  tests/data/pep_572_remove_parens.py
  tests/test_black.py
Labels: skip news

#2149 Maintainers += Richard Si (aka ichard26)
  README.md
Labels: skip news

#2151 Update CHANGELOG for 21.4b1 release
  CHANGES.md
  src/black_primer/primer.json
Labels: skip news

#2152 Add pyanalyze and typeshed to black-primer
  src/black_primer/primer.json
Labels: skip news

#2132 Add automatic version tagging to Docker CI Pushes
  .github/workflows/docker.yml
Labels: skip news

#2161 Remove useless shebangs in non-executable files
  src/black_primer/cli.py
  src/black_primer/lib.py
Labels: skip news

#2162 Update CHANGELOG for 21.4b2 release
  CHANGES.md
Labels: skip news
