Repository psf/black, pull requests merged in 2021-12, with the labels that each got.

#2617 release docs: slightly better example link
  docs/contributing/release_process.md
Labels: skip news

#2472 Treat functions/classes in blocks as if they're nested
  CHANGES.md
  src/black/lines.py
  src/black_primer/primer.json
  tests/data/function2.py
Labels: F: empty lines

#2663 remove regex dependency
  CHANGES.md
  Pipfile
  Pipfile.lock
  docs/integrations/editors.md
  setup.py
  src/black/trans.py
Labels: C: installation / packaging, C: dependencies

#2669 Reorganize changelog
  CHANGES.md
Labels: skip news

#2671 blib2to3 can raise TokenError and IndentationError too
  src/black/parsing.py
Labels: skip news

#2673 Prepare for release 21.12b0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: C: installation / packaging, skip news

#2674 no longer expect changes on pyanalyze
  src/black_primer/primer.json
Labels: skip news

#2676 chore: dump docs deps and pre-commit hooks
  .github/dependabot.yml
  .pre-commit-config.yaml
  docs/requirements.txt
Labels: C: dependencies, skip news

#2694 use valid package-ecosystem key
  .github/dependabot.yml
Labels: skip news

#2693 Include underlying error when AST safety check parsing fails
  CHANGES.md
  src/black/__init__.py
  tests/test_black.py
Labels: C: parser

#2701 Use 'python -m build' to build wheel and source distributions
  .github/workflows/pypi_upload.yml
Labels: C: installation / packaging, skip news

#2714 Define is name token to resolve some `type: ignore`s
  src/black/__init__.py
  src/black/linegen.py
  src/black/nodes.py
Labels: skip news

#2717 Remove usage of Pipenv, rely on good ol' `pip` and `virtualenv` in docs
  Pipfile
  Pipfile.lock
  docs/contributing/the_basics.md
Labels: skip news

#2719 Update contributing wording
  docs/contributing/the_basics.md
Labels: skip news

#2720 remove type: ignores in src/black/parsing.py
  src/black/linegen.py
  src/black/parsing.py
Labels: skip news

#2705 Support pytest 7
  tests/optional.py
  tests/test_ipynb.py
  tests/test_no_ipynb.py
Labels: skip news, C: maintenance

#2735 Primer: exclude crashing sqlalchemy file for now
  src/black_primer/primer.json
Labels: skip news
