Repository psf/black, pull requests merged in 2021-10, with the labels that each got.

#2510 MNT: remove unnecessary test deps + some refactoring
  Pipfile
  Pipfile.lock
  test_requirements.txt
  tests/test_black.py
  tests/test_format.py
  tests/util.py
Labels: C: cleanup, skip news, C: maintenance

#2519 Bump typed-ast minimum to 1.4.3 for 3.10 compat
  CHANGES.md
  Pipfile
  Pipfile.lock
  setup.py
Labels: C: dependencies

#2521 Use official Python 3.10 for CI jobs
  .github/workflows/fuzz.yml
  .github/workflows/primer.yml
  .github/workflows/test.yml
Labels: skip news, C: maintenance

#2574 fix: allow tests to be run from the tests/ directory
  tests/test_black.py
  tests/test_ipynb.py
Labels: skip news, C: maintenance

#2577 Add Tesla to organizations list
  README.md
Labels: T: documentation, skip news

#2575 Use STDIN project in test_projects to ensure it runs quickly
  tests/test_primer.py
Labels: skip news, C: maintenance

#2538 Update bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: skip news

#2579 Pin regex in docker to 2021.10.8
  CHANGES.md
  Dockerfile
Labels: C: installation / packaging, C: maintenance

#2523 Deprecate Python 2 formatting support
  CHANGES.md
  docs/faq.md
  src/black/__init__.py
  src/black/mode.py
  src/blib2to3/pgen2/token.py
  tests/test_black.py
Labels: C: cleanup, C: maintenance
