Repository psf/black, pull requests merged in 2021-06, with the labels that each got.

#1940 Add `version` to github action (and rewrite the whole thing while at it)
  CHANGES.md
  action.yml
  action/Dockerfile
  action/entrypoint.sh
  action/main.py
  docs/integrations/github_actions.md
Labels: C: integrations

#2305 Go back to single core for test suite on CI
  .github/workflows/test.yml
  tox.ini
Labels: C: maintenance, skip news

#2288 [primer] Enable everything
  src/black_primer/lib.py
  src/black_primer/primer.json
Labels: skip news

#2306 Mention comment non-processing in documentation
  docs/the_black_code_style/current_style.md
  tests/data/comments2.py
Labels: skip news

#2285 Regression fix: leave R prefixes capitalization alone
  CHANGES.md
  src/black/linegen.py
  src/black/strings.py
  src/black/trans.py
  tests/data/long_strings__regression.py
  tests/data/string_prefixes.py
Labels: F: strings / docstrings

#2320 Fix flake8 configuration by switching from extend-ignore to ignore
  .flake8
  src/black/output.py
Labels: skip news

#2324 Don't run Docker workflow on push to forks
  .github/workflows/docker.yml
Labels: skip news

#2323 Add coverage files to gitignore
  .gitignore
Labels: skip news

#2325 Update CHANGES.md for 21.6b0 release
  CHANGES.md
Labels: skip news

#2326 Fix incorrect document referance
  .pre-commit-config.yaml
Labels: T: documentation, skip news

#2315 Add STDIN test to primer
  CHANGES.md
  src/black_primer/lib.py
  src/black_primer/primer.json
  tests/test_primer.py
Labels: C: command line / config, C: integrations

#1871 Find pyproject from vim relative to current file
  CHANGES.md
  autoload/black.vim
Labels: C: vim

#1869 Vim plugin fix string normalization option
  CHANGES.md
  autoload/black.vim
  plugin/black.vim
Labels: C: vim

#2330 Add EOF and trailing whitespace fixer to pre-commit config
  .gitignore
  .pre-commit-config.yaml
  docs/Makefile
  docs/_static/license.svg
  pyproject.toml
  src/black/py.typed
  tests/test.toml
Labels: skip news

#2333 Docs: no space is inserted to empty docstrings (#2249)
  docs/the_black_code_style/current_style.md
Labels: skip news

#2341 Add Duolingo to list of users
  README.md
Labels: skip news

#2331 Update pre-commit config
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
Labels: skip news

#2344 Get `click` types from main repo
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  tests/test_black.py
Labels: skip news
