Repository psf/black, pull requests merged in 2022-07, with the labels that each got.

#3149 Use RTD's new build process
  .readthedocs.yaml
Labels: T: documentation, skip news

#3155 Slightly loosen the stability policy to permit exceptional (and rare) changes for previously unformatted code
  CHANGES.md
  docs/the_black_code_style/index.md
Labels: T: documentation

#3166 Don't (ever) put a single-char closing docstring quote on a new line
  CHANGES.md
  src/black/linegen.py
  tests/data/preview/docstring_preview.py
Labels: F: strings / docstrings

#3164 Move to explicitly creating a new loop
  CHANGES.md
  src/black/__init__.py
Labels: T: bug

#3168 Actually disable docstring prefix normalization with -S + fix instability
  CHANGES.md
  src/black/linegen.py
  src/black/mode.py
  tests/data/miscellaneous/docstring_preview_no_string_normalization.py
  tests/data/simple_cases/docstring.py
  tests/test_format.py
Labels: F: strings / docstrings

#3170 Fix typo in black docs for --extend-exclude
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3173 configure strict pytest and filterwarnings=['error', ...
  pyproject.toml
Labels: skip news

#3174 add pypy-3.8 to test matrix
  .github/workflows/test.yml
Labels: skip news

#3175 filterwarnings=["errors", ... followup
  pyproject.toml
  tests/test_format.py
Labels: skip news, C: maintenance

#3180 Use underscores instead of a space in this test file's name, to be consistent.
  tests/data/preview_310/remove_newline_after_match.py
Labels: skip news, C: maintenance

#3191 Bump pre-commit hooks
  .pre-commit-config.yaml
Labels: skip news, C: maintenance

#3189 Consolidate test CI and add concurrency limits
  .github/workflows/doc.yml
  .github/workflows/fuzz.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .github/workflows/uvloop_test.yml
Labels: C: cleanup, skip news, C: maintenance

#3194 Vim: prefix messages with "Black:"
  CHANGES.md
  autoload/black.vim
Labels: C: vim

#3193 Remove blib2to3 grammar cache logging
  CHANGES.md
  src/blib2to3/pgen2/driver.py
Labels: C: blib2to3

#3190 Add sanity check to executable CD + more
  .github/workflows/upload_binary.yml
Labels: C: cleanup, skip news, C: maintenance

#3199 Move fuzz.py to scripts/
  scripts/fuzz.py
  tox.ini
Labels: C: cleanup, skip news
