Repository psf/black, pull requests merged in 2022-09, with the labels that each got.

#3247 docs: adds ExitStack alternative to future_style.md
  docs/conf.py
  docs/the_black_code_style/future_style.md
Labels: T: documentation, skip news

#3246 add preview flag in vim plugin
  CHANGES.md
  autoload/black.vim
  docs/integrations/editors.md
  plugin/black.vim
Labels: C: integrations, C: configuration, C: vim

#3259 Mitigate deprecation of aiohttp's `@middleware` decorator
  pyproject.toml
  src/blackd/middlewares.py
Labels: skip news, C: maintenance

#3258 Move 3.11 tests to install aiohttp without C extensions
  .github/workflows/test-311.yml
  pyproject.toml
  tests/test_blackd.py
  tox.ini
Labels: T: enhancement, C: packaging, skip news

#3266 [FIX] migrate-black.py: don't fail on binary files
  scripts/migrate-black.py
Labels: skip news

#3270 Improve order of paragraphs on line splitting
  docs/the_black_code_style/current_style.md
Labels: T: documentation, skip news

#3272 Fix mypyc build errors on newer manylinux2014_x86_64 images
  pyproject.toml
Labels: skip news

#3276 Build mypyc wheels for CPython 3.11
  .github/workflows/pypi_upload.yml
  CHANGES.md
  pyproject.toml
  src/black/files.py
Labels: C: performance, C: packaging

#3274 Make context manager examples in future style docs consistent
  docs/the_black_code_style/future_style.md
Labels: skip news

#3285 Make README logo link to docs
  README.md
Labels: skip news

#3233 Switch build backend to Hatchling
  .github/mypyc-requirements.txt
  .github/workflows/diff_shades.yml
  .github/workflows/fuzz.yml
  .github/workflows/pypi_upload.yml
  .github/workflows/test.yml
  CHANGES.md
  MANIFEST.in
  docs/faq.md
  docs/usage_and_configuration/the_basics.md
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
Labels: C: packaging, C: maintenance

#3286 Fix outdated references to 3.6 and run pyupgrade
  README.md
  docs/getting_started.md
  docs/integrations/editors.md
  pyproject.toml
  src/black/comments.py
  src/black/concurrency.py
  src/black/trans.py
Labels: C: packaging, skip news, C: maintenance

#3275 Always call freeze_support() if sys.frozen is True
  CHANGES.md
  src/black/__init__.py
Labels: C: packaging

#3282 Add option to format Jupyter Notebooks files in GitHub Actions
  AUTHORS.md
  CHANGES.md
  action.yml
  action/main.py
  docs/integrations/github_actions.md
Labels: C: integrations

#3295 note that the CHANGELOG can be found at CHANGES.md for the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip news

#3297 Enable build isolation under CIWB
  pyproject.toml
Labels: skip news, C: maintenance
