Repository psf/black, pull requests merged in 2022-04, with the labels that each got.

#2989 Fix broken link in README.md
  README.md
Labels: skip news

#2993 Update test_black.shhh_click test for click 8+
  .pre-commit-config.yaml
  tests/test_black.py
Labels: skip news, C: maintenance

#2982 Update FAQ: Mention formatting of custom jupyter cell magic
  docs/faq.md
Labels: skip news

#2995 Top PyPI Packages: Use 30-days data, 365 is no longer available
  gallery/gallery.py
Labels: skip news

#3002 Explain our use of mypyc in the FAQ
  docs/faq.md
Labels: T: documentation, skip news

#3007 Quote "black[jupyter]" in README.md
  README.md
Labels: skip news

#3006 Quote black[jupyter] and black[d] in installation docs
  docs/getting_started.md
  docs/usage_and_configuration/black_as_a_server.md
Labels: skip news

#3008 Make ipynb tests compatible with ipython 8.3.0+
  tests/test_ipynb.py
Labels: skip news

#3023 Updated Black Docker Hub link in docs (#3022)
  docs/usage_and_configuration/black_docker_image.md
Labels: skip news

#3041 Stop pinning lark-parser
  tox.ini
Labels: skip news, C: maintenance
