Repository psf/black, pull requests merged in 2022-01, with the labels that each got.

#2733 Documentations: Wing IDE 8 integrations
  docs/integrations/editors.md
Labels: T: documentation, skip news

#2753 Improve CLI reference wording
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2736 Stubs: preserve blank line between attributes and methods
  CHANGES.md
  src/black/lines.py
  tests/data/stub.pyi
Labels: F: empty lines

#2765 Change installation url to comply with git security change
  docs/getting_started.md
Labels: skip news

#2769 don't expect changes on poetry
  src/black_primer/primer.json
Labels: skip news

#2297 Normalise string prefix order
  CHANGES.md
  docs/the_black_code_style/current_style.md
  src/black/strings.py
  src/blib2to3/pgen2/tokenize.py
  tests/data/string_prefixes.py
Labels: F: strings / docstrings

#2763 Don't make redundant copies of the DFA
  src/blib2to3/pgen2/parse.py
Labels: C: performance, skip news, C: parser

#2725 CI: add diff-shades integration
  .github/workflows/diff_shades.yml
  .github/workflows/diff_shades_comment.yml
  .pre-commit-config.yaml
  docs/contributing/gauging_changes.md
  scripts/diff_shades_gha_helper.py
Labels: skip news, C: maintenance

#2772 Dont require typing-extensions in 3.10
  CHANGES.md
  setup.py
Labels: skip news

#2775 [trivial] Use proper test cases on `unittest`
  tests/test_black.py
  tests/test_primer.py
Labels: skip news

#2778 Fix typo in diff_shades.yml workflow
  .github/workflows/diff_shades.yml
Labels: skip news

#2752 Create --preview CLI flag
  CHANGES.md
  docs/contributing/the_basics.md
  docs/the_black_code_style/future_style.md
  docs/the_black_code_style/index.rst
  src/black/__init__.py
  src/black/mode.py
  tests/test_format.py
Labels: T: design, C: command line / config, stable

#2773 Fix and speedup diff-shades integration
  .github/mypyc-requirements.txt
  .github/workflows/diff_shades.yml
  .github/workflows/diff_shades_comment.yml
  docs/contributing/gauging_changes.md
  scripts/diff_shades_gha_helper.py
  src/black/parsing.py
Labels: skip news, C: maintenance

#2786 Hint at likely cause of ast parsing failure in error message
  src/black/__init__.py
Labels: skip news

#2792 Add wind technology software projects using black
  README.md
Labels: skip news

#2793 Docs: switch to Furo
  CHANGES.md
  docs/_static/custom.css
  docs/conf.py
  docs/faq.md
  docs/index.rst
  docs/requirements.txt
Labels: T: documentation

#2739 Allow setting custom cache directory on all platforms with environmen…
  CHANGES.md
  docs/contributing/reference/reference_functions.rst
  docs/usage_and_configuration/file_collection_and_discovery.md
  src/black/cache.py
  tests/test_black.py
Labels: C: command line / config

#2794 Mark Felix and Batuhan as maintainers
  AUTHORS.md
Labels: T: documentation, skip news

#2796 Refactor logic for stub empty lines
  src/black/lines.py
Labels: skip news

#2797 Mention "skip news" label in changelog action
  .github/workflows/changelog.yml
Labels: skip news

#2758 Enable pattern matching by default
  CHANGES.md
  src/black/parsing.py
  src/blib2to3/pgen2/grammar.py
  src/blib2to3/pygram.py
  tests/test_format.py
Labels: C: parser, C: target version

#2800 Allow blackd to be run as a package
  src/blackd/__main__.py
Labels: skip news

#2801 Remove Beta mentions in README + Docs
  README.md
  docs/faq.md
  docs/index.rst
Labels: T: documentation, skip news

#2802 Use `magic_trailing_comma` for `FileMode` in `fuzz`
  fuzz.py
Labels: skip news

#2806 Fix crash on some power hugging cases
  src/black/linegen.py
  src/black/lines.py
  src/blib2to3/pytree.py
  tests/data/power_op_newline.py
  tests/test_format.py
Labels: skip news

#2810 more trailing comma tests
  tests/data/trailing_comma_optional_parens1.py
Labels: skip news

#2816 Tests for unicode identifiers
  fuzz.py
  tests/data/tricky_unicode_symbols.py
Labels: skip news

#2790 reorganize release notes for 22.1.0
  CHANGES.md
Labels: skip news

#2815 torture test
  tests/data/torture.py
  tests/test_format.py
Labels: skip news

#2818 Formalise style preference description
  docs/the_black_code_style/current_style.md
  docs/the_black_code_style/index.rst
Labels: skip news

#2822 Add a test case to torture.py
  tests/data/torture.py
Labels: skip news

#2823 Update classifiers to reflect stable
  setup.py
Labels: skip news

#2824 Remove test suite from setup.py
  setup.py
Labels: skip news

#2826 Prepare docs for release 22.1.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#2833 Adjust `--preview` documentation
  src/black/__init__.py
Labels: skip news

#2837 release process: formalize the changelog template
  CHANGES.md
  docs/contributing/release_process.md
Labels: skip news
