Repository psf/black, pull requests merged in 2022-08, with the labels that each got.

#3202 makes install available for all users in docker image
  CHANGES.md
  Dockerfile
Labels: C: integrations

#3205 Remove invalid syntax in test
  tests/data/miscellaneous/docstring_preview_no_string_normalization.py
Labels: skip news, C: maintenance

#3220 Use --no-implicit-optional for type checking
  mypy.ini
  src/blib2to3/pgen2/parse.py
Labels: skip news

#3197 Port & upstream mypyc wheel build workflow
  .github/mypyc-requirements.txt
  .github/workflows/pypi_upload.yml
  pyproject.toml
  setup.py
Labels: skip news, C: maintenance

#3209 Strip trailing commas in subscripts with -C
  CHANGES.md
  src/black/lines.py
  src/black/mode.py
  tests/data/preview/skip_magic_trailing_comma.py
  tests/test_format.py
Labels: F: trailing comma

#3235 Update email
  AUTHORS.md
Labels: skip news

#3234 Add passing 3.11 CI by exempting blackd tests
  .github/workflows/test-311.yml
  CHANGES.md
  setup.py
  tests/test_blackd.py
  tox.ini
Labels: T: enhancement, C: integrations

#3226 Removed need for subprocess call in `action.yml`
  AUTHORS.md
  action.yml
Labels: C: integrations, C: cleanup, skip news

#3162 Add parens around implicit string concatenations where increases readability
  CHANGES.md
  src/black/trans.py
  tests/data/preview/comments7.py
  tests/data/preview/long_strings.py
  tests/data/preview/long_strings__regression.py
  tests/test_black.py
Labels: F: parentheses, F: strings

#3222 Use strict mypy checking
  .pre-commit-config.yaml
  mypy.ini
  scripts/fuzz.py
  src/blackd/middlewares.py
  src/blib2to3/pytree.py
  tests/optional.py
  tests/test_blackd.py
Labels: skip news

#3237 Use .gitignore files in the initial source directories
  CHANGES.md
  src/black/__init__.py
  tests/test_black.py
Labels: T: bug, C: file collection

#3242 Improve & update release process to reflect recent changes
  docs/contributing/release_process.md
  docs/faq.md
  docs/the_black_code_style/index.md
Labels: T: documentation, skip news, C: maintenance

#3223 Update stable branch after publishing to PyPI
  .github/workflows/pypi_upload.yml
Labels: skip news, C: maintenance

#3248 Prepare docs for release 22.8.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news
