Repository psf/black, pull requests merged in 2022-12, with the labels that each got.

#3412 Fix CI with latest flake8-bugbear
  .flake8
Labels: skip news

#3411 release: skip bad macos wheels for now
  .github/workflows/pypi_upload.yml
Labels: skip news

#3413 Prepare release 22.12.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3416 fix(type): type annotation
  src/black/__init__.py
Labels: skip news

#3394 make black[jupyter] installation cross-shell
  README.md
  docs/getting_started.md
  src/black/handle_ipynb_magics.py
  tests/test_no_ipynb.py
Labels: T: documentation, skip news

#3380 Bump mypy[c] from 0.971 to 0.991
  .pre-commit-config.yaml
  CHANGES.md
  pyproject.toml
Labels: C: packaging

#3439 Fix a crash when a colon line is marked between `# fmt: off` and `# fmt: on`
  CHANGES.md
  src/black/comments.py
  tests/data/simple_cases/fmtonoff5.py
Labels: C: invalid code, F: fmtoff

#3444 Fix an infinite recursion error.
  src/black/linegen.py
  tests/data/preview/long_dict_values.py
Labels: skip news

#3446 Remove separate 3.11 CI now deps support 3.11
  .github/workflows/fuzz.yml
  .github/workflows/test-311.yml
  .github/workflows/test.yml
  CHANGES.md
Labels: skip news

#3461 Do not move docker `latest_release` tag for Pre-Releases
  .github/workflows/docker.yml
Labels: T: bug, C: packaging, skip news, C: maintenance

#3474 Ss18/pr0 typos
  docs/contributing/issue_triage.md
  tests/data/preview/prefer_rhs_split.py
Labels: C: cleanup, skip news

#2278 Parenthesize conditional expressions
  CHANGES.md
  src/black/__init__.py
  src/black/linegen.py
  src/black/mode.py
  tests/data/conditional_expression.py
Labels: F: parentheses

#3477 Fail lint CI if the PR doesn't target main
  .github/workflows/lint.yml
Labels: skip news, C: maintenance
