Repository psf/black, pull requests merged in 2022-02, with the labels that each got.

#2848 Surface links to Stability Policy
  CHANGES.md
  README.md
Labels: skip news

#2851 Isolate command line tests from user-level config
  tests/test_black.py
Labels: skip news, C: maintenance

#2858 Update description for GitHub Action `options:` argument
  action.yml
Labels: skip news

#2855 Putting our foot down for the Nth time (a.k.a. Indentation IV: electric hullabaloo)
  docs/faq.md
Labels: skip news

#2875 Add Django in 'used by' section in Readme
  README.md
Labels: T: documentation, skip news

#2870 Order the disabled error codes for pylint.
  docs/guides/using_black_with_other_tools.md
Labels: skip news

#2860 Update file_collection_and_discovery.md
  docs/usage_and_configuration/file_collection_and_discovery.md
Labels: skip news

#2854 Isolate command line tests for notebooks from user-level config
  tests/test_ipynb.py
Labels: skip news

#2853 correct Vim integration code
  docs/integrations/editors.md
Labels: C: vim, skip news

#2889 Format ourselves in preview mode
  pyproject.toml
  src/black/__init__.py
  tests/test_ipynb.py
Labels: skip news

#2890 separate CHANGELOG section for preview style
  CHANGES.md
  docs/contributing/release_process.md
Labels: skip news

#2895 fix new formatting issue
  src/black/__init__.py
Labels: skip news
