Repository psf/black, pull requests merged in 2022-06, with the labels that each got.

#3096 Fix minor typo
  scripts/migrate-black.py
Labels: skip news

#3118 Update documentation dependencies
  docs/conf.py
  docs/requirements.txt
Labels: T: documentation, C: dependencies, skip news, C: maintenance

#3069 use is_number_token insteaed of assertion
  src/black/__init__.py
  src/black/nodes.py
Labels: skip news

#3121 Bump actions/setup-python from 3 to 4
  .github/workflows/diff_shades.yml
  .github/workflows/diff_shades_comment.yml
  .github/workflows/doc.yml
  .github/workflows/fuzz.yml
  .github/workflows/lint.yml
  .github/workflows/pypi_upload.yml
  .github/workflows/test.yml
  .github/workflows/upload_binary.yml
  .github/workflows/uvloop_test.yml
Labels: skip news

#3114 Test run black on self
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  tests/test_format.py
  tox.ini
Labels: skip news

#3125 Replace link to Requests documentation
  README.md
Labels: T: documentation, skip news

#3135 Only call get_future_imports when needed.
  src/black/__init__.py
Labels: C: performance, skip news

#3136 Update preview style docs to include recent changes
  docs/the_black_code_style/future_style.md
Labels: skip news

#3139 Prepare docs for release 22.6.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: T: documentation, skip news

#3142 Fix typo in CHANGES.md
  CHANGES.md
Labels: skip news
