Repository psf/black, pull requests merged in 2022-10, with the labels that each got.

#3293 add \.ipynb_checkpoints to DEFAULT_EXCLUDES
  CHANGES.md
  src/black/const.py
Labels: C: configuration, C: file collection

#3311 Prepare release 22.10.0
  CHANGES.md
  docs/faq.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3313 Remove redundant 3.6 code and bump mypy's python_version to 3.7
  autoload/black.vim
  mypy.ini
  src/black/__init__.py
  src/black/concurrency.py
  src/black/parsing.py
Labels: skip news

#3326 Fix license metadata to follow PEP 621
  AUTHORS.md
  pyproject.toml
Labels: C: packaging, skip news

#3328 remove unreachable code
  src/black/parsing.py
Labels: skip news

#3325 Clarify check argument is needed for github action workflow
  docs/integrations/github_actions.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3284 Update README.md
  README.md
Labels: T: documentation, skip news

#3361 docs(readme): add Archer Aviation to organizations
  README.md
Labels: T: documentation, skip news
