Repository psf/black, pull requests merged in 2023-10, with the labels that each got.

#3910 Fix up changelog
  CHANGES.md
Labels: skip news

#3913 docs: use LSP for SublimeText 4
  docs/integrations/editors.md
Labels: skip news

#3921 Update link to VS Code formatting instructions
  docs/integrations/editors.md
Labels: skip news

#3917 exclude tests/data/.* from mypy
  mypy.ini
Labels: skip news

#3884 Remove `$`, `>>>` and other prompt prefixes when code copied from the…
  docs/conf.py
Labels: skip news

#3927 Set Docker to use 3.11 for now
  Dockerfile
Labels: skip news

#3939 Fix test that was not being run
  tests/data/cases/conditional_expression.py
Labels: skip news

#3945 CI Test: Deprecating 'Healthcheck.all()' from Hypothesis in fuzz.py
  scripts/fuzz.py
Labels: skip news

#3936 Migrate mypy config to pyproject.toml
  .gitignore
  .pre-commit-config.yaml
  mypy.ini
  pyproject.toml
  scripts/check_pre_commit_rev_in_example.py
  scripts/check_version_in_basics_example.py
  scripts/diff_shades_gha_helper.py
  scripts/fuzz.py
  scripts/make_width_table.py
  src/blackd/__init__.py
  tests/optional.py
  tests/test_blackd.py
Labels: skip news

#3951 Prepare release 23.10.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3963 Fixed typo in CHANGES.md
  CHANGES.md
Labels: skip news

#3965 Move Docker image to hatch + compile
  CHANGES.md
  Dockerfile
  docs/usage_and_configuration/black_docker_image.md
Labels: C: packaging, C: cleanup

#3961 docs: specifies the use of the .git-blame-ignore-revs file
  docs/guides/introducing_black_to_your_project.md
Labels: skip news

#3969 Prepare release 23.10.1
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: T: enhancement, skip news

#3973 Add Unreleased template to CHANGES.md
  CHANGES.md
Labels: skip news

#3979 Fix typo in future_style.md
  docs/the_black_code_style/future_style.md
Labels: skip news

#3984 Fix CI by running on Python 3.11
  .github/workflows/diff_shades.yml
  .github/workflows/doc.yml
  .github/workflows/lint.yml
Labels: skip news

#3985 docs: fix typos in change log and documentations
  CHANGES.md
  docs/the_black_code_style/current_style.md
Labels: skip news

#3990 Update current_style.md
  docs/the_black_code_style/current_style.md
Labels: skip news

#3991 Add trailing comma test case for hugging parens
  docs/the_black_code_style/future_style.md
  tests/data/cases/preview_hug_parens_with_braces_and_square_brackets.py
Labels: skip news

#3988 Update CHANGES.md
  CHANGES.md
Labels: skip news

#3995 Update README.md
  README.md
Labels: skip news

#3993 Regression test for match variable inside match
  tests/data/cases/pattern_matching_complex.py
Labels: skip news

#3997 Update README.md
  README.md
Labels: skip news

#3974 Add release tool
  .github/workflows/release_tests.yml
  docs/contributing/release_process.md
  scripts/release.py
  scripts/release_tests.py
Labels: skip news
