Repository psf/black, pull requests merged in 2023-03, with the labels that each got.

#1879 Improve multiline string handling
  CHANGES.md
  docs/the_black_code_style/future_style.md
  src/black/linegen.py
  src/black/lines.py
  src/black/mode.py
  tests/data/preview/multiline_strings.py
Labels: help wanted, F: strings, S: up for grabs

#3599 Correct Spelling Mistakes
  autoload/black.vim
  docs/contributing/issue_triage.md
  src/blib2to3/pgen2/driver.py
  tests/data/preview/long_strings.py
  tests/data/simple_cases/comments4.py
Labels: skip news

#3567 Update documentation regarding isort compatibility
  docs/guides/using_black_with_other_tools.md
Labels: skip news

#3615 Fix bug introduced in #3564.
  src/black/lines.py
Labels: skip news

#3543 Use GH action version when version argument not specified
  .git_archival.txt
  .gitattributes
  CHANGES.md
  action/main.py
Labels: C: integrations

#3625 Prepare release 23.3.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3628 Fixup the changelog
  CHANGES.md
Labels: skip news
