Repository psf/black, pull requests merged in 2023-09, with the labels that each got.

#3858 Move coverage configurations to `pyproject.toml`
  .coveragerc
  .github/workflows/test.yml
  pyproject.toml
Labels: skip news

#3558 (🐞) blackd: fix issue for mishandling single character input
  CHANGES.md
  src/blackd/__init__.py
  tests/test_blackd.py
Labels: S: awaiting response

#3839 Add Black PyCharm 2023.2 integration instructions
  docs/integrations/editors.md
Labels: skip news

#3863 Prepare release 23.9.0
  CHANGES.md
  docs/contributing/release_process.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3866 Add classifier for 3.12
  pyproject.toml
Labels: skip news

#3868 Bump RTD Python version from 3.8 to 3.11
  .readthedocs.yaml
Labels: T: documentation, C: dependencies, skip news

#3871 Add mypyc test marks to new tests that patch
  tests/test_black.py
Labels: skip news

#3873 Upgrade to Furo 2023.9.10 to fix docs build
  docs/requirements.txt
Labels: skip news

#3876 Ignore aiohttp DeprecationWarning for 3.12
  pyproject.toml
Labels: skip news

#3875 Re-export black.Mode
  src/black/__init__.py
  tests/test_black.py
Labels: skip news

#3870 mypyc builds on PRs, skip mypyc wheels for 3.12
  .github/workflows/pypi_upload.yml
  pyproject.toml
Labels: skip news

#3878 Prepare release 23.9.1
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3885 Fix broken url in editors.md
  docs/integrations/editors.md
Labels: skip news

#3881 mypyc build improvements
  .github/workflows/pypi_upload.yml
  pyproject.toml
Labels: skip news

#3888 Document disabling E704
  .flake8
  docs/guides/using_black_with_other_tools.md
  docs/the_black_code_style/current_style.md
Labels: skip news

#3896 Remove outdated mentions of runtime support of Python 3.7
  README.md
  autoload/black.vim
  docs/faq.md
  docs/getting_started.md
  docs/integrations/editors.md
Labels: skip news

#3898 added the py311 to target-version config
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3902 add support for printing the diff of AST trees when running tests
  docs/contributing/the_basics.md
  src/black/debug.py
  tests/conftest.py
  tests/test_black.py
  tests/util.py
  tox.ini
Labels: skip news
