Repository psf/black, pull requests merged in 2023-07, with the labels that each got.

#3770 Fix CI for Click typing issue
  .github/workflows/diff_shades.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: skip news

#3768 Remove click patch
  CHANGES.md
  docs/contributing/reference/reference_functions.rst
  src/black/__init__.py
  src/blackd/__init__.py
  tests/test_black.py
Labels: skip news

#3771 Run pyupgrade on blib2to3 and src
  src/black/files.py
  src/black/handle_ipynb_magics.py
  src/blib2to3/pgen2/conv.py
  src/blib2to3/pgen2/driver.py
  src/blib2to3/pgen2/grammar.py
  src/blib2to3/pgen2/literals.py
  src/blib2to3/pgen2/parse.py
  src/blib2to3/pgen2/pgen.py
  src/blib2to3/pgen2/token.py
  src/blib2to3/pgen2/tokenize.py
  src/blib2to3/pygram.py
  src/blib2to3/pytree.py
Labels: skip news

#3723 Add CITATION.cff file
  CHANGES.md
  CITATION.cff
Labels: skip news

#3775 Upgrade to latest mypy
  .pre-commit-config.yaml
Labels: skip news

#3777 Disable coverage on pypy tests
  .github/workflows/test.yml
  tox.ini
Labels: skip news

#3772 Unpin pytest-xdist
  test_requirements.txt
Labels: skip news

#3776 Prepare release 23.7.0
  CHANGES.md
  docs/integrations/source_version_control.md
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3779 Fix typo in CITATION.cff
  CITATION.cff
Labels: T: documentation, skip news

#3784 Remove Python 3.7 from classifiers
  pyproject.toml
Labels: skip news

#3783 Remove unneeded mypy dependencies
  .pre-commit-config.yaml
Labels: skip news

#3781 Fix lint in test_ipynb
  tests/test_ipynb.py
Labels: skip news

#3787 Update documentation about comments to include mention of hashbangs.
  docs/the_black_code_style/current_style.md
Labels: skip news

#3791 Continue to avoid Click typing issue
  .pre-commit-config.yaml
Labels: skip news

#3792 Maintainers += Shantanu Jain (hauntsaninja)
  AUTHORS.md
Labels: T: documentation, skip news

#3794 Fix most blib2to3 lint
  .pre-commit-config.yaml
  pyproject.toml
  src/blib2to3/README
  src/blib2to3/pgen2/driver.py
  src/blib2to3/pgen2/literals.py
  src/blib2to3/pgen2/parse.py
  src/blib2to3/pgen2/pgen.py
  src/blib2to3/pgen2/token.py
  src/blib2to3/pgen2/tokenize.py
  src/blib2to3/pygram.py
  src/blib2to3/pytree.py
Labels: skip news

#3799 Fix diff-shades comment missing newlines
  scripts/diff_shades_gha_helper.py
Labels: skip news, C: maintenance

#3753 Doc: a few small updates on [Contributing/The basics.md]
  docs/contributing/the_basics.md
Labels: skip news

#3797 Simplify empty line tracker
  src/black/lines.py
Labels: skip news

#3804 Fixing pre-commit is using pyyaml with broken version
  .pre-commit-config.yaml
Labels: skip news

#3809 Fix unintentionally swapped words in index.md
  docs/index.md
Labels: skip news

#3810 Refactoring the assert statement.
  tests/test_trans.py
Labels: skip news

#3818 Add Lyft to organizations using black
  README.md
Labels: skip news
