Repository psf/black, pull requests merged in 2023-01, with the labels that each got.

#3478 Add email for Richard Si
  AUTHORS.md
Labels: T: documentation, skip news

#3492 Remove misleading phrase in Usage and Configuration
  docs/usage_and_configuration/the_basics.md
Labels: skip news

#3488 Documentation: clarify the state of multiple context managers.
  docs/the_black_code_style/future_style.md
Labels: skip news

#3365 Add IntelliJ docs on external tools and file watcher
  docs/integrations/editors.md
Labels: T: documentation, C: integrations, skip news

#3451 Fix two docstring crashes
  CHANGES.md
  src/black/linegen.py
  tests/data/miscellaneous/linelength6.py
  tests/data/simple_cases/docstring.py
  tests/test_format.py
Labels: skip news

#3503 Add flake8-bugbear B907 to ignore list
  .flake8
Labels: skip news

#3511 Reenable macOS mypyc wheel build
  .github/workflows/pypi_upload.yml
Labels: C: performance, C: packaging, skip news

#3513 Use dashes for pycodestyle max line length config
  docs/guides/using_black_with_other_tools.md
Labels: skip news

#2916 Format hex code in unicode escape sequences in string literals
  CHANGES.md
  src/black/linegen.py
  src/black/mode.py
  src/black/strings.py
  tests/data/preview/format_unicode_escape_seq.py
Labels: T: design, F: strings

#3520 Update document now that paren wrapping CMs on Python 3.9+ is implemented
  docs/the_black_code_style/future_style.md
Labels: skip news

#3528 Update Python version in the_basics.md
  docs/contributing/the_basics.md
Labels: skip news

#3534 Upgrade isort
  .pre-commit-config.yaml
Labels: skip news
