Repository psf/black, pull requests merged in 2025-06, with the labels that each got.

#4690 Fix f-string format spec CI failure
  tests/data/cases/pep_701.py
Labels: skip news

#4691 Prerelease improvements
  docs/contributing/release_process.md
  scripts/release.py
Labels: skip news

#4692 Small cleanup to parsing.py
  src/black/parsing.py
Labels: C: cleanup, skip news

#4693 Improve line ranges docs note
  docs/usage_and_configuration/the_basics.md
Labels: T: documentation, skip news

#4697 CI: Replace unsupported windows-2019 with window-2025
  .github/workflows/upload_binary.yml
Labels: skip news

#4432 Add default exclusions and inclusions to docs
  docs/usage_and_configuration/the_basics.md
Labels: skip news
